remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Ardian91's homepage
description: I am an Informatics student at Insititut Teknologi Sepuluh Nopember. Currently on my third year of studying. Stay tune for my amazing upcoming projects!
email: "ardianstudent@gmail.com"
